AlexXJeanpier/Proyecto-de-gestion-de-Hotel

include/gestion.h

El prototipo ha de incluir las funciones que va a contener gestion.h

gestion.h: Se creo un prototipo

---

src/mantenimiento.cpp

Ideas para mantenimiento.cpp: 
**INICIAR:**
- Ingresar numero de pisos
- Ingresar categorias
- Mostrar categorias ingresadas
- Ingresar numero de habitaciones por piso
- Asignar categorias a cada habitacion
- Mostrar categorias asignadas a las habitaciones
**EDITAR:**
- Visualizar datos de inicio registrado
- Agregar pisos
- Agregar habitaciones 
- Agregar categorias
- Cambiar categoria de una habitacion
**VISUALIZAR:**
- Visualizar inicio registrado

mantenimiento.cpp: Se agrego estructura base

---

include/gestion.h

Se añadió la estructura que se ha de usar, también la primera función  a implementar.

gestion.h: agregando la funcion registrar_usuario

---

include/mantenimiento.h

**FUNCIONES:**
- Iniciar
- Editar
- Visualizar

mantenimiento.h: se declararon las funciones

---

src/gestion.cpp

Todavía no se ha implementado el arreglo de estructura global

gestion.cpp: Solicitud de datos del usuario

---

src/mantenimiento.cpp

El usuario ahora podra ingresar el numero de pisos, el numero de categorias y el nombre de cada categoria

mantenimiento.cpp: ingresar numero de pisos y categorias

---

include/mantenimiento.h

Variables globales externas para categorias y pisos

mantenimiento.h: se agregaron variables globales externas

---

src/panel.cpp

Añadiendo un menu al panel

---

src/mantenimiento.cpp

Ahora se puede mostrar todas las categorias que agrego el usuario

mantenimiento.cpp: mostrar las categorias ingresadas

---

src/mantenimiento.cpp

El usuario ahora puede ingresar el numero de habitaciones que tiene cada piso

mantenimiento.cpp: ingresar numero de habitaciones por piso

---

src/panel.cpp

Añadiendo una función más al panel

Añadiendo una funcion más al panel

---

src/panel.cpp

Añadiendo una función interfaz al panel

Añadiendo una funcion interfaz al panel

---

src/mantenimiento.cpp

El usuario ahora puede asignar una categoria previamente ingresada a cada habitacion

mantenimiento.cpp: asignar categoria a cada habitacion

---

include/mantenimiento.h

Se agrego struct piso y se borro using namespace std

mantenimiento.h: se agrego struct piso

---

src/mantenimiento.cpp

Se elimino duplicacion de struct piso en mantenimiento.cpp porque ya se encuentra en mantenimiento.h

mantenimiento.cpp: se elimino duplicacion de struct piso

---

src/mantenimiento.cpp

Se puede mostrar la categoria asignada para cada una de las habitaciones

mantenimiento.cpp: mostrar categorias asignadas a cada habitacion

---

src/mantenimiento.cpp

Imprimir encabezado de cada piso para luego colocar las habitaciones en columnas

mantenimiento.cpp: imprimir encabezado de cada piso

---

src/mantenimiento.cpp

El numero y categoria de cada habitacion se imprime en columnas debajo del encabezado de cada piso

mantenimiento.cpp: imprimir la informacion de cada habitacion por piso

---

include/gestion.h

usuario esta relacionada con el registro de tipo USUARIO, todo cambio en la función va a afectar al registro.

gestion.h: Se agrego una variable por referencia en el parámetro de la función

---

src/mantenimiento.cpp

Se agrego una nueva funcion para manejar el menu de mantenimiento

mantenimiento.cpp: se agrego el menu de mantenimiento

---

include/mantenimiento.h

Se agrego la funcion "mantenimiento()" a "mantenimiento.h"

mantenimiento.h: se declaro una nueva funcion para gestionar el menu

---

src/mantenimiento.cpp

Nuevos nombres: CATEGORIA y PISO

mantenimiento.cpp: se cambio el nombre de algunos arreglos

---

src/mantenimiento.cpp

El usuario ahora puede ingresar el precio junto a la categoria de cada habitacion

mantenimiento.cpp: ingresar precios de cada habitacion

---

src/mantenimiento.cpp

Se muestran precios de cada habitacion junto a la categoria

mantenimiento.cpp: mostrar precios de cada habitacion

---

src/mantenimiento.cpp

Se asignaron los precios basandose en la categoria para luego mostrar ambos datos juntos

mantenimiento.cpp: asignar precio basado en la categoria

---

src/panel.cpp

Moviendo función para saber si esta ocupado una habitación

Moviendo función para saber si esta ocupado una habitacion

---

src/mantenimiento.cpp

Se creo un menu para la funcion editar donde se podra agregar pisos y categorias

mantenimiento.cpp: se agrego un menu para la opcion editar

---

src/panel.cpp

Mejorando la función mostrarPanel

Mejorando la funcion mostrarPanel

---

src/gestion.cpp

También se uso la recursividad en las funciones de gestion.cpp

gestion.cpp: Se agregaron las funciones de las librerias panel.h y mantenimiento.h

---

src/cafeteria.cpp

Mejorando función venderProductos

Mejorando funcion venderProductos

---

src/cafeteria.cpp

Mejorando funcion cafeteria

---

include/cafeteria.h
src/cafeteria.cpp

cambios de Rama5

---

include/gestion.h

Se busca tener todo en estructura.h y estructura.cpp (registros y arreglos globales)

gestion.h: Se elimino los registros y arreglos

---

include/estructura.h

Se busca tener todo en estructura.h y estructura.cpp (registros y arreglos globales)

Se trasladaron las variables y registros en estructura.h

---

src/gestion.cpp

if(usuarios[i].DNI==dni) , recorriendo el registro se observo el error ya que buscaba un DNI pero no uno en especifico por eso la creación de dni para almacenar el valor del arreglo usuarios del tipo DNI

buscar_usuarioPorDNI: Se corrigio la condicional para hallar el DNI

---

src/reportes.cpp

se rezalizo unos cambios graficos para dicha interfaz

Rama reportes

---

src/gestion.cpp

visualizarCategorias(): función de mantenimiento para saber los precios (lo muestra de manera superficial mejorar eso)
mostrarPanel() : función de panel que muestra una perspectiva del hotel, si las habitaciones están ocupadas (1) o si están desocupadas (0)

reservarHabitacion: Se uso funciones de mantenimiento.h y panel.h

---

src/gestion.cpp

Al haber sido modificado del tipo int a void se agrego una validación mas en dicha funcion (reservarHabitacion)

reservarHabitacion: como la funcion buscar dni no devuelve un valor se hicieron cambios

---

src/main.cpp
src/mantenimiento.cpp

A causa de que  if(agregarAhora='s'||agregarAhora='S'), agregar habitación adquiría ese valor no lo comparaba, como se buscaba desde un inicio

Modificaciones en el case1 del switch.

---

src/panel.cpp
src/reportes.cpp

No se podía compilar por que resulta que no había una instancia deuda en el registro USUARIO

En panel se modificaron las variables en reportes se pudo usar deuda

---

src/cafeteria.cpp

mejorando la función venderProducto

mejorando la función venderProducto

---

src/cafeteria.cpp

Mejorando la función venderProductos por segunda vez

Mejorando la funcion venderProductos por segunda vez

---

src/cafeteria.cpp

Mejorando algunas cosas
